%macro EXIT 0-1 0
mov rdi, %1 ; код завершения программы
mov rax, 60 ; номер функции exit
syscall
%endmacro
%macro READ 2-3 0
mov rax, %3 ; файловый ввод
mov rdi, %3 ; 
mov rsi, %1 ; адрес вводимых данных
mov rdx, %2 ; размер вводимых данных
syscall
%endmacro
%macro WRITE 2-3 1
mov rax, %3 ; файловый вывод
mov rdi, %3 ; файловый дескриптор
mov rsi, %1 ; адрес выводимых данных
mov rdx, %2 ; размер выводимых данных
syscall
%endmacro		
